name:                downloader
version:             0.1.0.1
github:              "deech/downloader"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "Aditya Siram, 2019"
category:            network, file
synopsis:            A small, low-dependency library that provides turn-key file download over HTTP and HTTPS.
extra-source-files:
- README.org

description:         Please see the Hackage documentation at <http://hackage.haskell.org/package/downloader/docs/Network-HTTP-Download-File.html>

dependencies:
- base >= 4.7 && < 5
- safe >= 0.3.16 && < 0.4
data-files:
  - scripts/download.sh
  - scripts/download.ps1

library:
  source-dirs: src
  dependencies:
    - process >= 1.4.0.0 && < 1.7
    - network-uri >= 2.6.1.0 && < 2.7
    - directory >= 1.3.2.0 && < 1.3.5
    - filepath >= 1.4.2 && < 1.4.3
